version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: quadratic-api
