name: Lint Check
on: push

jobs:
  call-setup:
    uses: ./.github/workflows/setup.yml

  lint:
    runs-on: ubuntu-latest-4-cores

      - name: Run Prettier
        run: npm run lint:prettier

      - name: Run EsLint
        run: npm run lint:eslint

      - name: Run TypeScript
        run: npm run lint:ts
