name: Lint Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest-4-cores

    steps:
      - uses: actions/checkout@v2

      - name: Cache wasm-pack build
        uses: actions/cache@v2
        with:
          path: |
            quadratic-core/target
            quadratic-core/pkg
          key: ${{ runner.os }}-wasm-pack
          restore-keys: |
            ${{ runner.os }}-wasm-pack

      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'

      - name: Update local rust toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Quadratic
        run: |
          npm run build:wasm
          npm install

      - name: Run Prettier
        run: npm run lint:prettier

      - name: Run EsLint
        run: npm run lint:eslint

      - name: Run TypeScript
        run: npm run lint:ts
