name: Lint Check
on: push

jobs:
  lint:
    runs-on: ubuntu-latest-4-cores

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup.yml

      - name: Run Prettier
        run: npm run lint:prettier

      - name: Run EsLint
        run: npm run lint:eslint

      - name: Run TypeScript
        run: npm run lint:ts
