name: Lint Check
on: push

jobs:
  lint:
    uses: ./.github/workflows/setup.yml
    runs-on: ubuntu-latest-4-cores

    steps:
      - name: Run Prettier
        run: npm run lint:prettier

      - name: Run EsLint
        run: npm run lint:eslint

      - name: Run TypeScript
        run: npm run lint:ts
