name: Setup Quadratic
on: workflow_call

jobs:
  setup_quadratic:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'

      - name: Update local rust toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Quadratic
        run: |
          npm run build:wasm
          npm install
