name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_unit:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '19'
          cache: 'npm'

      - name: Update local rust toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - run: npm run build:wasm:nodejs
      - run: npm install
      - run: npm run test:unit:ci
