name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_unit:
    runs-on: ubuntu-latest-4-cores

    steps:
      - uses: actions/checkout@v2

      - name: Cache quadratic-core build
        uses: actions/cache@v2
        with:
          path: |
            quadratic-core/target
            quadratic-core/pkg
          key: ${{ runner.os }}-quadratic-core-unit
          restore-keys: |
            ${{ runner.os }}-quadratic-core-unit

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v2
        with:
          node-version: '19'
          cache: 'npm'
      - name: Update local rust toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - run: npm config set registry https://registry.npmjs.cf/
      - run: npm install

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          npm run build:wasm:nodejs

      - run: npm run test:unit:ci
