name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest-4-cores

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '19'
          cache: 'npm'
      - name: Update local rust toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - run: npm install

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          npm run build:wasm:nodejs

      - name: Upload quadratic-core build
        uses: actions/upload-artifact@v2
        with:
          name: quadratic-core
          path: quadratic-core/pkg/

  test_unit:
    needs: build
    runs-on: ubuntu-latest-4-cores

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '19'
          cache: 'npm'

      - name: Download quadratic-core build
        uses: actions/download-artifact@v2
        with:
          name: quadratic-core
          path: quadratic-core/pkg/

      - run: npm install

      - run: npm run test:unit:ci

  lint:
    needs: build
    runs-on: ubuntu-latest-4-cores

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '19'
          cache: 'npm'

      - name: Download quadratic-core build
        uses: actions/download-artifact@v2
        with:
          name: quadratic-core
          path: quadratic-core/pkg/

      - run: npm install

      - name: Run Prettier
        run: npm run lint:prettier

      - name: Run EsLint
        run: npm run lint:eslint

      - name: Run TypeScript
        run: npm run lint:ts
